services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      # Uncomment the next line if you are on an M1/M2 Mac and need to force AMD64 images
      # platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/yourdatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # Uncomment the next line if you are on an M1/M2 Mac and need to force AMD64 images
      # platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdatabase
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql-data:
