version: '3.8'

services:
  # Spring Boot backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/yourdatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    # Optionally, you can use a volume to persist the target artifacts across restarts
    volumes:
      - ./target:/app/target

  # Vue frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # MySQL database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdatabase
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql-data:
