services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      # Uncomment the next line if you are on an M1/M2 Mac and need to force AMD64 images
      # platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/yourdatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=hello123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy  # Wait for DB healthcheck
    # Optionally, you can use a volume to persist the target artifacts across restarts
    volumes:
      - ./target:/app/target

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # Uncomment the next line if you are on an M1/M2 Mac and need to force AMD64 images
      # platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: yourdatabase
      MYSQL_ROOT_PASSWORD: hello123
      MYSQL_ROOT_HOST: '%'  # Add this line
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -phello123"]  # Fixed command
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql-data:
