spring:
  datasource:
    url: jdbc:mysql://mysql:3306/planFlights?createDatabaseIfNotExist=True
    username: root
    password: hello123
  jpa:
    show -sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
