spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planFlights?createDatabaseIfNotExist=True
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show -sql: true
    database-platform: org.hibernate.dialect.MySQLDialect